package report

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"pipelineguard/internal/parsers"
)

// sarifDoc mirrors the subset of the emitted SARIF document the tests inspect.
// The tests unmarshal the generated bytes into this struct rather than doing
// string comparisons.
type sarifDoc struct {
	Schema  string `json:"$schema"`
	Version string `json:"version"`
	Runs    []struct {
		Tool struct {
			Driver struct {
				Name  string `json:"name"`
				Rules []struct {
					ID               string `json:"id"`
					ShortDescription struct {
						Text string `json:"text"`
					} `json:"shortDescription"`
				} `json:"rules"`
			} `json:"driver"`
		} `json:"tool"`
		Results []struct {
			RuleID  string `json:"ruleId"`
			Level   string `json:"level"`
			Message struct {
				Text string `json:"text"`
			} `json:"message"`
			Properties struct {
				OriginTool string `json:"originTool"`
			} `json:"properties"`
			Locations []struct {
				PhysicalLocation struct {
					ArtifactLocation struct {
						URI string `json:"uri"`
					} `json:"artifactLocation"`
					Region *struct {
						StartLine int `json:"startLine"`
					} `json:"region"`
				} `json:"physicalLocation"`
			} `json:"locations"`
		} `json:"results"`
	} `json:"runs"`
}

func mustParseSARIF(t *testing.T, findings []parsers.Finding) sarifDoc {
	t.Helper()
	raw, err := GenerateSARIF(findings)
	require.NoError(t, err)

	var doc sarifDoc
	require.NoError(t, json.Unmarshal(raw, &doc), "output must be valid JSON")

	assert.Equal(t, "2.1.0", doc.Version)
	assert.Equal(t, sarifSchemaURL, doc.Schema)
	require.Len(t, doc.Runs, 1)
	assert.Equal(t, "PipelineGuard", doc.Runs[0].Tool.Driver.Name)
	return doc
}

func TestGenerateSARIF_EmptyFindings(t *testing.T) {
	raw, err := GenerateSARIF(nil)
	require.NoError(t, err)

	// Arrays must be [] and never null.
	assert.Contains(t, string(raw), `"results": []`)
	assert.Contains(t, string(raw), `"rules": []`)
	assert.NotContains(t, string(raw), "null")

	doc := mustParseSARIF(t, nil)
	assert.Empty(t, doc.Runs[0].Results)
	assert.Empty(t, doc.Runs[0].Tool.Driver.Rules)
	assert.NotNil(t, doc.Runs[0].Results)
	assert.NotNil(t, doc.Runs[0].Tool.Driver.Rules)
}

func TestGenerateSARIF_FindingWithLine(t *testing.T) {
	doc := mustParseSARIF(t, []parsers.Finding{
		{
			Tool:     "gitleaks",
			Severity: "CRITICAL",
			File:     "config/settings.py",
			Line:     12,
			Rule:     "generic-api-key",
			Message:  "Generic API Key",
		},
	})

	require.Len(t, doc.Runs[0].Results, 1)
	res := doc.Runs[0].Results[0]
	require.Len(t, res.Locations, 1)

	region := res.Locations[0].PhysicalLocation.Region
	require.NotNil(t, region, "region must be present when Line > 0")
	assert.Equal(t, 12, region.StartLine)
	assert.Equal(t, "config/settings.py", res.Locations[0].PhysicalLocation.ArtifactLocation.URI)
}

func TestGenerateSARIF_FindingWithoutLine(t *testing.T) {
	doc := mustParseSARIF(t, []parsers.Finding{
		{
			Tool:     "trivy",
			Severity: "MEDIUM",
			File:     "go.sum",
			Line:     0,
			Rule:     "CVE-2023-99999",
			Message:  "example vuln",
		},
	})

	require.Len(t, doc.Runs[0].Results, 1)
	res := doc.Runs[0].Results[0]
	require.Len(t, res.Locations, 1)
	assert.Nil(t, res.Locations[0].PhysicalLocation.Region, "region must be omitted when Line == 0")
	assert.Equal(t, "go.sum", res.Locations[0].PhysicalLocation.ArtifactLocation.URI)

	// Belt and suspenders: the raw bytes carry no "region" key at all.
	raw, err := GenerateSARIF([]parsers.Finding{
		{Tool: "trivy", Severity: "MEDIUM", File: "go.sum", Line: 0, Rule: "CVE-2023-99999", Message: "example vuln"},
	})
	require.NoError(t, err)
	assert.NotContains(t, string(raw), "region")
}

func TestGenerateSARIF_SeverityToLevelMapping(t *testing.T) {
	cases := map[string]string{
		"CRITICAL":    "error",
		"HIGH":        "error",
		"MEDIUM":      "warning",
		"LOW":         "note",
		"INFO":        "none",
		"MADE-UP-SEV": "warning",
	}

	for severity, wantLevel := range cases {
		severity, wantLevel := severity, wantLevel
		t.Run(severity, func(t *testing.T) {
			doc := mustParseSARIF(t, []parsers.Finding{
				{Tool: "trivy", Severity: severity, File: "f", Line: 1, Rule: "r-" + severity, Message: "m"},
			})
			require.Len(t, doc.Runs[0].Results, 1)
			assert.Equal(t, wantLevel, doc.Runs[0].Results[0].Level)
		})
	}
}

func TestGenerateSARIF_RulesDeduplicatedByRule(t *testing.T) {
	doc := mustParseSARIF(t, []parsers.Finding{
		{Tool: "gitleaks", Severity: "CRITICAL", File: "a.py", Line: 1, Rule: "generic-api-key", Message: "Generic API Key"},
		{Tool: "gitleaks", Severity: "CRITICAL", File: "b.py", Line: 5, Rule: "generic-api-key", Message: "a different message, must be ignored"},
		{Tool: "trivy", Severity: "HIGH", File: "go.sum", Line: 0, Rule: "CVE-1", Message: "cve one"},
	})

	rules := doc.Runs[0].Tool.Driver.Rules
	require.Len(t, rules, 2, "generic-api-key must appear only once")

	byID := map[string]string{}
	for _, r := range rules {
		byID[r.ID] = r.ShortDescription.Text
	}
	assert.Equal(t, "Generic API Key", byID["generic-api-key"], "shortDescription comes from the first finding with that rule")
	assert.Equal(t, "cve one", byID["CVE-1"])

	// All three findings still produce a result.
	assert.Len(t, doc.Runs[0].Results, 3)
}

func TestGenerateSARIF_OriginToolPropagated(t *testing.T) {
	doc := mustParseSARIF(t, []parsers.Finding{
		{Tool: "gitleaks", Severity: "CRITICAL", File: "a.py", Line: 1, Rule: "generic-api-key", Message: "Generic API Key"},
		{Tool: "trivy", Severity: "HIGH", File: "go.sum", Line: 0, Rule: "CVE-1", Message: "cve one"},
	})

	require.Len(t, doc.Runs[0].Results, 2)
	byRule := map[string]string{}
	for _, res := range doc.Runs[0].Results {
		byRule[res.RuleID] = res.Properties.OriginTool
	}
	assert.Equal(t, "gitleaks", byRule["generic-api-key"])
	assert.Equal(t, "trivy", byRule["CVE-1"])
}
